version: '3'
services:
  traffic_backend:
    container_name: traffic_backend
    image: traffic_image
    build: .
    restart: always
    ports:
      - "3303:8080"
    links:
      - mongodb
    environment:
    - DATABASE_URL=mongodb://mongodb:27017/traffic


  mongodb:
    container_name: mongodb
    image: mongo:3.6
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/mongodb